const actionsType = {
    TOGGLE_MODE:'TOGGLE_MODE',
    CHANGE_BOARD:'CHANGE_BOARD',
    CHECK_SUBTASK:'CHECK_SUBTASK',
    CHANGE_COLUMN:'CHANGE_COLUMN',
    ADD_BOARD:'ADD_BOARD',
    ADD_COLUMN:'ADD_COLUMN',
    ADD_TASK:'ADD_TASK',
}

export default actionsType;